import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const caustenFont = localFont({
  src: "../public/fonts/Causten-Regular.otf",
  display: "swap",
});

const coreSanFont = localFont({
  src: "../public/fonts/Fontspring-DEMO-coresansc35.otf",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${caustenFont.className} ${coreSanFont.className}`}>
        {children}
      </body>
    </html>
  );
}
