import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const causten = localFont({
  src: "../public/fonts/Causten-Regular.otf",
  display: "swap",
  variable: "--font-causten",
});

const coreSan = localFont({
  src: "../public/fonts/Fontspring-DEMO-coresansc35.otf",
  display: "swap",
  variable: "--font-coreSan",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${causten.variable} ${coreSan.variable}`}>
        {children}
      </body>
    </html>
  );
}
